### ISSUE TITLE
Import shaders and textures error for male body

### ISSUE THREAD

**Issue by lurkingaround** [FlailingFog/KK-Blender-Shader-Pack#58]
```
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-96f66e8414a9f8452b6a31000f44d5efdb461dd3\importing\importeverything.py", line 770, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-96f66e8414a9f8452b6a31000f44d5efdb461dd3\importing\importeverything.py", line 383, in get_and_load_textures
    imageLoad('Template Body', 'Gentex', 'BodyMC', 'cf_m_body_ColorMask.png')
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-96f66e8414a9f8452b6a31000f44d5efdb461dd3\importing\importeverything.py", line 373, in imageLoad
    currentObj.material_slots[mat].material.node_tree.nodes[group].node_tree.nodes[node].image = bpy.data.images[image]
KeyError: 'bpy_prop_collection[key]: key "Template Body" not found'

location: <unknown location>:-1


```

**Comment by FlailingFog** [comment]
Is there something like a cf_m_body_00.00**2** material when you import the .pmx file? And does it accidentally get put on the Clothes object when you get to the hair separation part?

**Comment by lurkingaround** [comment]
Yes, cm_m_body -28400 does get moved to the clothes objects.
![body](https://user-images.githubusercontent.com/88926467/140632098-83c6c05e-0096-4fac-b1b0-eebaec551ade.png)
![body2](https://user-images.githubusercontent.com/88926467/140632100-e6e0a53c-9cb7-4c0b-bb73-7832642e6918.png)

**Comment by lurkingaround** [comment]
```
Python: Traceback (most recent call last):
  File "C:\Users\Fabyan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 781, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\Fabyan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 392, in get_and_load_textures
    imageLoad('Template Body', 'Gentex', 'BodyMC', 'cf_m_body_ColorMask.png')
  File "C:\Users\Fabyan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 381, in imageLoad
    currentObj.material_slots[mat].material.node_tree.nodes[group].node_tree.nodes[node].image = bpy.data.images[image]
KeyError: 'bpy_prop_collection[key]: key "Template Body" not found'

location: <unknown location>:-1


```
f84840

**Comment by lurkingaround** [comment]
```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 781, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 392, in get_and_load_textures
    imageLoad('Template Body', 'Gentex', 'BodyMC', 'cf_m_body_ColorMask.png')
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 381, in imageLoad
    currentObj.material_slots[mat].material.node_tree.nodes[group].node_tree.nodes[node].image = bpy.data.images[image]
KeyError: 'bpy_prop_collection[key]: key "Template Body" not found'

location: <unknown location>:-1


```

f848408

**Comment by lurkingaround** [comment]
```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 790, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 392, in get_and_load_textures
    imageLoad('Template Body', 'Gentex', 'BodyMC', 'cf_m_body_ColorMask.png')
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\importeverything.py", line 381, in imageLoad
    currentObj.material_slots[mat].material.node_tree.nodes[group].node_tree.nodes[node].image = bpy.data.images[image]
KeyError: 'bpy_prop_collection[key]: key "Template Body" not found'

location: <unknown location>:-1


```
9901a03

**Comment by FlailingFog** [comment]
This is happening because the cm_m_body material and the c_m_shadowcast material are getting the '-####' tags added onto the material name / image files.

@MediaMoots 
Could you remove the tags for these materials in the exporter?

**Comment by MediaMoots** [comment]
ok

**Comment by MediaMoots** [comment]
nvm, found the issue

**Comment by MediaMoots** [comment]
PR #79 should fix the material issues.
Please let me know if it doesn't.

**Comment by lurkingaround** [comment]
Just tested and working perfectly. Thank you very much.
